- name: configuring catalogue
  become: yes
  hosts: catalogue
  tasks:
  - name: disable node js
    ansible.builtin.command:
      dnf module disable nodejs -y
  - name: enable node js
    ansible.builtin.command:
      dnf module enable nodejs:20 -y
  - name: install node js
    ansible.builtin.package:
      name: nodejs
      state: present
  - name: creating roboshop user
    ansible.builtin.user:
      name: roboshop
      shell: /sbin/nologin
      home: /app

  - name: creating app directory
    ansible.builtin.file:
      path: /app
      state: directory
  - name: getting the url
    ansible.builtin.get_url:
      url: https://roboshop-artifacts.s3.amazonaws.com/catalogue-v3.zip
      dest: /tmp/catalogue.zip
  - name: extracting the code
    ansible.builtin.unarchive:
      src: /tmp/catalogue.zip
      dest: /app
      remote_src: yes
  - name: install dependencies
    community.general.npm:
      path: /app
  - name: copying repo
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service
  - name: loading the service
    ansible.builtin.systemd_service:
      daemon_reload: true
  - name: start and enable catalogue
    ansible.builtin.service:
      name: catalogue
      state: started
      enable: yes
  